In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('train.csv')

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.Gender.unique()


array(['Male', 'Female', nan], dtype=object)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [119]:
df.shape

(614, 13)

In [120]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df["Property_Area"].value_counts()

Semiurban    233
Urban        202
Rural        179
Name: Property_Area, dtype: int64

In [9]:
df.Dependents.fillna(1,inplace=True)
df.LoanAmount.fillna(df.LoanAmount.mean(),inplace=True)
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
Value_mapping={'Yes':1,'No':0}
df['Married_Section']=df.Married.map(Value_mapping)

In [17]:
Value_Mapping1 = {'Male' : 1, 'Female' : 0}
df['Gender_Section'] = df['Gender'].map(Value_Mapping1)
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  Gender_Section  Married_Section  
0             1.0         Urban           Y             1.0              0.0  
1             1.0         Rural           N             1.0              1.0  
2             1.0         Urban           Y             1.0              1.0  
3             1.0         Urban           Y             1.0              1.0  
4             1.0         Urban           Y             1.0              0.0

In [18]:
Value_Mapping2 = {'Graduate' : 1, 'Not Graduate' : 0}
df['Edu_Section'] = df['Education'].map(Value_Mapping2)

In [22]:
Value_Mapping3 = {'Yes' : 1, 'No' : 0}
df['Employed_Section'] = df['Self_Employed'].map(Value_Mapping3)

In [23]:
df["Married_Section"].fillna(df.Married_Section.mean(),inplace=True) 

df["Gender_Section"].fillna(df.Gender_Section.mean(),inplace=True)

df["Loan_Amount_Term"].fillna(df.Loan_Amount_Term.mean(),inplace=True)

df["Credit_History"].fillna(df.Credit_History.mean(),inplace=True)

In [24]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
Gender_Section        0
Married_Section       0
Edu_Section           0
Employed_Section     32
dtype: int64

In [25]:
df["Employed_Section"].fillna(df.Employed_Section.mean(),inplace=True)

In [27]:
Value_mapping4={'Urban':0,'Rural':1,'Semiurban':2}
df['property']=df.Property_Area.map(Value_mapping4)

In [28]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  Gender_Section  Married_Section  \
0             1.0         Urban           Y             1.0              0.0   
1             1.0         Rural           N             1.0              1.0   
2             1.0         Urban           Y             1.0              1.0   
3             1.0         Urban           Y             1.0              1.0   
4             1.0         Urban           Y             1.0              0.0   

   Edu_Section  Employed_Section  property  
0            1               0.0         0  
1            1               0.0         1  
2            1               1.0         0  
3            0               0.0         0  
4            1               0.0         0

In [54]:
df.Dependents=df.Dependents.replace('3+',3)

In [55]:
df1=df.drop(['Loan_ID','Gender','Married','Education','Property_Area','Self_Employed'],axis='columns')

df1.head()

In [57]:
df1.head(10)

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0          0             5849                0.0  146.412162   
1          1             4583             1508.0  128.000000   
2          0             3000                0.0   66.000000   
3          0             2583             2358.0  120.000000   
4          0             6000                0.0  141.000000   
5          2             5417             4196.0  267.000000   
6          0             2333             1516.0   95.000000   
7          3             3036             2504.0  158.000000   
8          2             4006             1526.0  168.000000   
9          1            12841            10968.0  349.000000   

   Loan_Amount_Term  Credit_History Loan_Status  Gender_Section  \
0             360.0             1.0           Y             1.0   
1             360.0             1.0           N             1.0   
2             360.0             1.0           Y             1.0   
3             360.0             1.0           Y             1.0   
4             360.0             1.0           Y             1.0   
5             360.0             1.0           Y             1.0   
6             360.0             1.0           Y             1.0   
7             360.0             0.0           N             1.0   
8             360.0             1.0           Y             1.0   
9             360.0             1.0           N             1.0   

   Married_Section  Edu_Section  Employed_Section  property  
0              0.0            1               0.0         0  
1              1.0            1               0.0         1  
2              1.0            1               1.0         0  
3              1.0            0               0.0         0  
4              0.0            1               0.0         0  
5              1.0            1               1.0         0  
6              1.0            0               0.0         0  
7              1.0            1               0.0         2  
8              1.0            1               0.0         0  
9              1.0            1               0.0         2

In [58]:
df1.shape

(614, 12)

In [59]:
x=df1.drop('Loan_Status',axis='columns')

In [60]:
y=df.Loan_Status

In [61]:
from sklearn.model_selection import cross_val_score

In [62]:
from sklearn.linear_model import LogisticRegression

In [64]:
cross_val_score(LogisticRegression(),x,y,cv=5)

D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.81451613, 0.75806452, 0.78688525, 0.86065574, 0.80327869])

In [65]:
from sklearn.svm import SVC
cross_val_score(SVC(),x,y,cv=5)

D:\python\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\python\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\python\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\python\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 's

array([0.68548387, 0.68548387, 0.69672131, 0.69672131, 0.68852459])

In [66]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(),x,y,cv=5)

D:\python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\python\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in vers

array([0.76612903, 0.72580645, 0.7704918 , 0.77868852, 0.75409836])

In [67]:
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(),x,y,cv=5)

array([0.67741935, 0.66129032, 0.72131148, 0.68852459, 0.74590164])

In [ ]:
cross_val_score(SVC(),x,y,cv=5)

In [68]:
model=LogisticRegression()
model.fit(x,y)

D:\python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [70]:
model.score(x,y)

0.8094462540716613

In [71]:
from sklearn.externals import joblib
joblib.dump(model,'model_joblib')

D:\python\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['model_joblib']

In [248]:
from sklearn.externals import joblib
joblib.dump(model,'model_joblib')

['model_joblib']